# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='date_of_birth',
            new_name='date_of_registration',
        ),
    ]
